"""empty message

Revision ID: 090f1232f0c0
Revises: 
Create Date: 2021-05-19 14:52:36.533707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '090f1232f0c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mail', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.Column('boolean', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('sexe', sa.String(length=15), nullable=True),
    sa.Column('firstname', sa.String(length=64), nullable=True),
    sa.Column('lastname', sa.String(length=64), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('mail', sa.String(length=64), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('nationality', sa.String(length=64), nullable=True),
    sa.Column('origin', sa.String(length=64), nullable=True),
    sa.Column('father_job', sa.String(length=64), nullable=True),
    sa.Column('mother_job', sa.String(length=64), nullable=True),
    sa.Column('father_origin', sa.String(length=64), nullable=True),
    sa.Column('mother_origin', sa.String(length=64), nullable=True),
    sa.Column('school', sa.String(length=64), nullable=True),
    sa.Column('future_job', sa.String(length=64), nullable=True),
    sa.Column('eye_color', sa.String(length=64), nullable=True),
    sa.Column('hair_color', sa.String(length=64), nullable=True),
    sa.Column('body', sa.String(length=64), nullable=True),
    sa.Column('religion', sa.String(length=64), nullable=True),
    sa.Column('torah', sa.String(length=64), nullable=True),
    sa.Column('jew_status', sa.String(length=64), nullable=True),
    sa.Column('sexe_1', sa.String(length=64), nullable=True),
    sa.Column('eye_color_1', sa.String(length=64), nullable=True),
    sa.Column('hair_color_1', sa.String(length=64), nullable=True),
    sa.Column('body_1', sa.String(length=64), nullable=True),
    sa.Column('religion_1', sa.String(length=64), nullable=True),
    sa.Column('torah_1', sa.String(length=64), nullable=True),
    sa.Column('jew_status_1', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candi')
    op.drop_table('user')
    # ### end Alembic commands ###
