"""empty message

Revision ID: 28ac45617782
Revises: a4ba68bb366f
Create Date: 2021-05-11 19:19:06.239345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28ac45617782'
down_revision = 'a4ba68bb366f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('sexe', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate', 'sexe')
    # ### end Alembic commands ###
