"""empty message

Revision ID: a4ba68bb366f
Revises: bedb26bdfa35
Create Date: 2021-05-11 12:43:50.496748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4ba68bb366f'
down_revision = 'bedb26bdfa35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('body', sa.String(length=64), nullable=True))
    op.add_column('candidate', sa.Column('body_1', sa.String(length=64), nullable=True))
    op.add_column('candidate', sa.Column('eye_color', sa.String(length=64), nullable=True))
    op.add_column('candidate', sa.Column('eye_color_1', sa.String(length=64), nullable=True))
    op.add_column('candidate', sa.Column('hair_color', sa.String(length=64), nullable=True))
    op.add_column('candidate', sa.Column('hair_color_1', sa.String(length=64), nullable=True))
    op.add_column('candidate', sa.Column('jew_status', sa.String(length=64), nullable=True))
    op.add_column('candidate', sa.Column('jew_status_1', sa.String(length=64), nullable=True))
    op.add_column('candidate', sa.Column('religion', sa.String(length=64), nullable=True))
    op.add_column('candidate', sa.Column('religion_1', sa.String(length=64), nullable=True))
    op.add_column('candidate', sa.Column('torah', sa.String(length=64), nullable=True))
    op.add_column('candidate', sa.Column('torah_1', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate', 'torah_1')
    op.drop_column('candidate', 'torah')
    op.drop_column('candidate', 'religion_1')
    op.drop_column('candidate', 'religion')
    op.drop_column('candidate', 'jew_status_1')
    op.drop_column('candidate', 'jew_status')
    op.drop_column('candidate', 'hair_color_1')
    op.drop_column('candidate', 'hair_color')
    op.drop_column('candidate', 'eye_color_1')
    op.drop_column('candidate', 'eye_color')
    op.drop_column('candidate', 'body_1')
    op.drop_column('candidate', 'body')
    # ### end Alembic commands ###
