"""empty message

Revision ID: bedb26bdfa35
Revises: 93befc34d598
Create Date: 2021-05-10 10:57:37.314084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bedb26bdfa35'
down_revision = '93befc34d598'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('mail', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate', 'mail')
    # ### end Alembic commands ###
