"""empty message

Revision ID: ecbd399e2b7e
Revises: 28ac45617782
Create Date: 2021-05-11 19:29:39.637819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecbd399e2b7e'
down_revision = '28ac45617782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('sexe_1', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate', 'sexe_1')
    # ### end Alembic commands ###
